- hosts: localhost
  connection: local
  become: sudo
  vars:
    fogkv_path: '/home/fogkv'
    fogkv_DAQDB_path: '/home/fogkv/daqdb_200405'
  tasks:


 ##### Install CVMFS
 # - Important to first install cvmfs-release in seperate task, not listing it with cvmfs in one task
  -  name: "Install cvmfs-release"
     become: sudo
     yum: 
       state:  present
       name: 
       -  https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
  -  name: "Install cvmfs"
     become: sudo
     yum: 
       state:  present
       name: 
       -  cvmfs
  -  name: Setup CVMFS
     shell: 
       cvmfs_config setup
  -  name: Setup cvmfs/default.local
     shell:
       echo "CVMFS_REPOSITORIES=sft.cern.ch" |  tee -a /etc/cvmfs/default.local
  -  name: Setup /etc/cvmfs/default.local
     shell:
       echo "CVMFS_HTTP_PROXY=http://ca-proxy.cern.ch:3128" |  tee -a /etc/cvmfs/default.local 
  -  name: Config CVMFS
     shell: |
       cvmfs_config probe
       ls -l /cvmfs/
       #ls /cvmfs/grid.cern.ch


