- hosts: localhost
  connection: local
  become: yes
  vars:
    fogkv_path: '/home/fogkv'
    fogkv_DAQDB_path: '/home/fogkv/daqdb-configuration-master'
  tasks:


##### Download code from github
  -  name: Download code from github
     shell: |
        cd '{{ fogkv_path }}/'
        mkdir daqdb_installation
        cd daqdb_installation  
        git clone https://github.com/daq-db/daqdb.git
        cd daqdb/
        git submodule update --init --recursive


