- hosts: localhost
  connection: local
  become: yes
  vars:
    fogkv_path: '/home/fogkv'
    fogkv_DAQDB_path: '/home/fogkv/daqdb_200406'
  tasks:
 


##### Download extra packages
# Modify third-party/spdk/scripts/pkgdep.sh by adding "--skip-broken" to libibverbs-devel librdmacm-devel line, remove libibverbs libibumad librdmacm
  -  name: "Remove libibverbs libibumad librdmacm and rdma-core-devel- they will be installed with running pkgdep.sh"
     yum:
       state:  absent
       name:
       -  libibverbs
       -  libibumad
       -  librdmacm
       -  rdma-core-devel
  -  name: "Run pkgdep.sh"
     shell: |
       cd '{{ fogkv_DAQDB_path }}/daqdb_installation/daqdb'
       ./scripts/pkgdep.sh
       grep -ir exclud /etc/yum.*
       third-party/spdk/scripts/pkgdep.sh
  -  name: "Remove boost devel to be able to install gtest-devel 1.8"
     yum:
       state:  absent
       name:
       -  boost-devel
  -  name: "Install asio-devel, cmake3, gtest-devel"
     yum:
       state:  present
       name:
       -  http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-1.noarch.rpm
       -  boost169-devel
       -  asio-devel
       -  cmake3
       -  gtest-devel

