- hosts: localhost
  connection: local
  become: yes
  vars:
    fogkv_path: '/home/fogkv'
    fogkv_DAQDB_path: '/home/fogkv/daqdb-configuration-master'
  tasks:
 

##### Install mellanox drivers 4.7.
##### http://www.mellanox.com/page/mlnx_ofed_eula?mtag=linux_sw_drivers&mrequest=downloads&mtype=ofed&mver=MLNX_OFED-5.0-1.0.0.0&mname=MLNX_OFED_LINUX-5.0-1.0.0.0-rhel7.7-x86_64.tgz
  -  name: "Download mellanox drivers 4.7"
     get_url:
       url: http://aabedabu.web.cern.ch/aabedabu/sites/resources/MLNX_OFED_LINUX-4.7-3.2.9.0-rhel7.7-x86_64.tgz
       dest: '{{ fogkv_path }}/daqdb_installation/daqdb/'
 # -  name: Extract mellanox drivers 4.7"
 #    unarchive:
 #      src: '{{ fogkv_path }}/MLNX_OFED_LINUX-4.7-3.2.9.0-rhel7.7-x86_64.tgz'
 #      dest: '{{ fogkv_path }}/daqdb_installation/daqdb/'
  -  name: "Install mellanox drivers 4.7."
     shell: |
       tar zxf MLNX_OFED_LINUX-4.7-3.2.9.0-rhel7.7-x86_64.tgz
       cd '{{ fogkv_path }}/daqdb_installation/daqdb/MLNX_OFED_LINUX-4.7-3.2.9.0-rhel7.7-x86_64'
       sudo ./mlnxofedinstall --add-kernel-support --dpdk
       /etc/init.d/openibd status



